services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30

  redis:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mongo_data:
  redis_data:
